version: "2.1"

services:



    pweb-db:
        container_name: "mysql"
        image: mysql:5.7
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: "password"
            MYSQL_DATABASE: "prisma"
        networks:
            - pweb-database-network
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 40s
            retries: 20



    pweb_frontend:
        build: pweb_frontend-master
        container_name: "pweb_frontend"
        ports:
            - 3000:3000
        networks:
            - internal-frontend-backend-network
        depends_on:
            - pweb_backend


    pweb_backend:
        build: pweb_backend-master
        container_name: "pweb_backend"
        command: "node server.js"
        restart: on-failure
        ports:
            - 3001:3001
        networks:
            - internal-frontend-backend-network
            - pweb-database-network
            - rmq_backend
        depends_on:
            - rabbitmq
        depends_on:
            pweb-db:
                condition: service_healthy
            

    pweb_backend_email:
        build: pweb_backend-master
        container_name: "email"
        command: "node jobs/emailJob.js"
        restart: on-failure
        networks:
            - rmq_email
        depends_on:
            - rabbitmq

    

    rabbitmq:
        image: rabbitmq:management-alpine
        container_name: "rabbitmq"
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            - rmq_backend
            - rmq_email
            - logging
        hostname: rabbitmq

    kong:
        image: kong:latest
        volumes:
            - ./Kong:/usr/local/kong/declarative
        environment:
            KONG_DATABASE: 'off'
            KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
            KONG_PROXY_ACCESS_LOG: /dev/stdout
            KONG_ADMIN_ACCESS_LOG: /dev/stdout
            KONG_PROXY_ERROR_LOG: /dev/stderr
            KONG_ADMIN_ERROR_LOG: /dev/stderr
            KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
        ports:
            - 80:8000
            - 443:8443
            - 8001:8001
            - 8444:8444
        deploy:
            placement:
                constraints: [node.role == manager]
        networks:
            - internal-frontend-backend-network
            - logging

    grafana:
      image: grafana/grafana:latest
      volumes:
        - ./grafana/data:/var/lib/grafana
      ports:
        - 3002:3000
      networks:
        - logging
    
    prometheus:
      image: prom/prometheus
      volumes:
        - ./prometheus/config.yml:/etc/prometheus/prometheus.yml
      ports:
        - 9090:9090
      networks:
        - logging


networks:
    internal-frontend-backend-network:
    pweb-database-network:
    rmq_backend:
    rmq_email:
    logging:
