version: "3.2"

services:
   

    agent:
        image: portainer/agent:2.11.1
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /var/lib/docker/volumes:/var/lib/docker/volumes
        networks:
          - agent_network
        deploy:
          mode: global
          placement:
            constraints: [node.platform.os == linux]

    portainer:
        image: portainer/portainer-ce:2.11.1
        command: -H tcp://tasks.agent:9001 --tlsskipverify
        ports:
          - "9443:9443"
          - "9000:9000"
          - "8000:8000"
        volumes:
          - portainer_data:/data
        networks:
          - agent_network
        deploy:
          mode: replicated
          replicas: 1
          placement:
            constraints: [node.role == manager]



networks:
    internal-frontend-backend-network:
    pweb-database-network:
    rmq:
    database-admin:
    internal:
    logging:
    agent_network:
        driver: overlay
        attachable: true

volumes:
  portainer_data:


#docker swarm init --advertise-addr 192.168.99.100
#docker stack deploy --compose-file portianer.yml  vossibility   
#docker stack deploy --compose-file docker-compose.yml  vossibility   

 #- name: build DB
     #   run: npx prisma migrate deploy 