export const languages = [
	'Afar',
	'Abkhaz',
	'Avestan',
	'Afrikaans',
	'Akan',
	'Amharic',
	'Aragonese',
	'Arabic',
	'Assamese',
	'Avaric',
	'Aymara',
	'Azerbaijani',
	'South Azerbaijani',
	'Bashkir',
	'Belarusian',
	'Bulgarian',
	'Bihari',
	'Bislama',
	'Bambara',
	'Bengali',
	' Bangla',
	'Tibetan Standard, Tibetan, Central',
	'Breton',
	'Bosnian',
	'Catalan',
	' Valencian',
	'Chechen',
	'Chamorro',
	'Corsican',
	'Cree',
	'Czech',
	'Old Church Slavonic, Church Slavonic, Old Bulgarian',
	'Chuvash',
	'Welsh',
	'Danish',
	'German',
	'Divehi',
	' Dhivehi',
	' Maldivian',
	'',
	'Dzongkha',
	'Ewe',
	'Greek, Modern',
	'English',
	'Esperanto',
	'Spanish',
	' Castilian',
	'Estonian',
	'Basque',
	'Persian (Farsi)',
	'Fula',
	' Fulah',
	' Pulaar',
	' Pular',
	'Finnish',
	'Fijian',
	'Faroese',
	'French',
	'Western Frisian',
	'Irish',
	'Scottish Gaelic',
	' Gaelic',
	'Galician',
	'Guaraní',
	'Gujarati',
	'Manx',
	'Hausa',
	'Hebrew (modern)',
	'Hindi',
	'Hiri Motu',
	'Croatian',
	'Haitian',
	' Haitian Creole',
	'Hungarian',
	'Armenian',
	'Herero',
	'Interlingua',
	'Indonesian',
	'Interlingue',
	'Igbo',
	'Nuosu',
	'Inupiaq',
	'Ido',
	'Icelandic',
	'Italian',
	'Inuktitut',
	'Japanese',
	'Javanese',
	'Georgian',
	'Kongo',
	'Kikuyu, Gikuyu',
	'Kwanyama, Kuanyama',
	'Kazakh',
	'Kalaallisut, Greenlandic',
	'Khmer',
	'Kannada',
	'Korean',
	'Kanuri',
	'Kashmiri',
	'Kurdish',
	'Komi',
	'Cornish',
	'Kyrgyz',
	'Latin',
	'Luxembourgish, Letzeburgesch',
	'Ganda',
	'Limburgish, Limburgan, Limburger',
	'Lingala',
	'Lao',
	'Lithuanian',
	'Luba-Katanga',
	'Latvian',
	'Malagasy',
	'Marshallese',
	'Māori',
	'Macedonian',
	'Malayalam',
	'Mongolian',
	'Marathi (Marāṭhī)',
	'Malay',
	'Maltese',
	'Burmese',
	'Nauru',
	'Norwegian Bokmål',
	'North Ndebele',
	'Nepali',
	'Ndonga',
	'Dutch',
	'Norwegian Nynorsk',
	'Norwegian',
	'South Ndebele',
	'Navajo, Navaho',
	'Chichewa',
	' Chewa',
	' Nyanja',
	'Occitan',
	'Ojibwe, Ojibwa',
	'Oromo',
	'Oriya',
	'Ossetian, Ossetic',
	'Panjabi, Punjabi',
	'Pāli',
	'Polish',
	'Pashto, Pushto',
	'Portuguese',
	'Quechua',
	'Romansh',
	'Kirundi',
	'Romanian',
	'Russian',
	'Kinyarwanda',
	'Sanskrit (Saṁskṛta)',
	'Sardinian',
	'Sindhi',
	'Northern Sami',
	'Sango',
	'Sinhala, Sinhalese',
	'Slovak',
	'Slovene',
	'Samoan',
	'Shona',
	'Somali',
	'Albanian',
	'Serbian',
	'Swati',
	'Southern Sotho',
	'Sundanese',
	'Swedish',
	'Swahili',
	'Tamil',
	'Telugu',
	'Tajik',
	'Thai',
	'Tigrinya',
	'Turkmen',
	'Tagalog',
	'Tswana',
	'Tonga (Tonga Islands)',
	'Turkish',
	'Tsonga',
	'Tatar',
	'Twi',
	'Tahitian',
	'Uyghur, Uighur',
	'Ukrainian',
	'Urdu',
	'Uzbek',
	'Venda',
	'Vietnamese',
	'Volapük',
	'Walloon',
	'Wolof',
	'Xhosa',
	'Yiddish',
	'Yoruba',
	'Zhuang, Chuang',
	'Chinese',
	'Zulu'
];

export const countries = [
	'Afghanistan',
	'Åland Islands',
	'Albania',
	'Algeria',
	'American Samoa',
	'Andorra',
	'Angola',
	'Anguilla',
	'Antarctica',
	'Antigua And Barbuda',
	'Argentina',
	'Armenia',
	'Aruba',
	'Australia',
	'Austria',
	'Azerbaijan',
	'Bahamas',
	'Bahrain',
	'Bangladesh',
	'Barbados',
	'Belarus',
	'Belgium',
	'Belize',
	'Benin',
	'Bermuda',
	'Bhutan',
	'Bolivia',
	'Bosnia And Herzegovina',
	'Botswana',
	'Bouvet Island',
	'Brazil',
	'British Indian Ocean Territory',
	'Brunei Darussalam',
	'Bulgaria',
	'Burkina Faso',
	'Burundi',
	'Cambodia',
	'Cameroon',
	'Canada',
	'Cape Verde',
	'Cayman Islands',
	'Central African Republic',
	'Chad',
	'Chile',
	'China',
	'Christmas Island',
	'Cocos (Keeling) Islands',
	'Colombia',
	'Comoros',
	'Congo',
	'Congo, The Democratic Republic Of The',
	'Cook Islands',
	'Costa Rica',
	"Cote D'ivoire",
	'Croatia',
	'Cuba',
	'Cyprus',
	'Czechia',
	'Denmark',
	'Djibouti',
	'Dominica',
	'Dominican Republic',
	'Ecuador',
	'Egypt',
	'El Salvador',
	'Equatorial Guinea',
	'Eritrea',
	'Estonia',
	'Ethiopia',
	'Falkland Islands (Malvinas)',
	'Faroe Islands',
	'Fiji',
	'Finland',
	'France',
	'French Guiana',
	'French Polynesia',
	'French Southern Territories',
	'Gabon',
	'Gambia',
	'Georgia',
	'Germany',
	'Ghana',
	'Gibraltar',
	'Greece',
	'Greenland',
	'Grenada',
	'Guadeloupe',
	'Guam',
	'Guatemala',
	'Guernsey',
	'Guinea',
	'Guinea-bissau',
	'Guyana',
	'Haiti',
	'Heard Island And Mcdonald Islands',
	'Holy See (Vatican City State)',
	'Honduras',
	'Hong Kong',
	'Hungary',
	'Iceland',
	'India',
	'Indonesia',
	'Iran, Islamic Republic Of',
	'Iraq',
	'Ireland',
	'Isle Of Man',
	'Israel',
	'Italy',
	'Jamaica',
	'Japan',
	'Jersey',
	'Jordan',
	'Kazakhstan',
	'Kenya',
	'Kiribati',
	"Korea, Democratic People's Republic Of",
	'Korea, Republic Of',
	'Kuwait',
	'Kyrgyzstan',
	"Lao People's Democratic Republic",
	'Latvia',
	'Lebanon',
	'Lesotho',
	'Liberia',
	'Libyan Arab Jamahiriya',
	'Liechtenstein',
	'Lithuania',
	'Luxembourg',
	'Macao',
	'Macedonia, The Former Yugoslav Republic Of',
	'Madagascar',
	'Malawi',
	'Malaysia',
	'Maldives',
	'Mali',
	'Malta',
	'Marshall Islands',
	'Martinique',
	'Mauritania',
	'Mauritius',
	'Mayotte',
	'Mexico',
	'Micronesia, Federated States Of',
	'Moldova, Republic Of',
	'Monaco',
	'Mongolia',
	'Montenegro',
	'Montserrat',
	'Morocco',
	'Mozambique',
	'Myanmar',
	'Namibia',
	'Nauru',
	'Nepal',
	'Netherlands',
	'Netherlands Antilles',
	'New Caledonia',
	'New Zealand',
	'Nicaragua',
	'Niger',
	'Nigeria',
	'Niue',
	'Norfolk Island',
	'Northern Mariana Islands',
	'Norway',
	'Oman',
	'Pakistan',
	'Palau',
	'Palestinian Territory, Occupied',
	'Panama',
	'Papua New Guinea',
	'Paraguay',
	'Peru',
	'Philippines',
	'Pitcairn',
	'Poland',
	'Portugal',
	'Puerto Rico',
	'Qatar',
	'Reunion',
	'Romania',
	'Russian Federation',
	'Rwanda',
	'Saint Helena',
	'Saint Kitts And Nevis',
	'Saint Lucia',
	'Saint Pierre And Miquelon',
	'Saint Vincent And The Grenadines',
	'Samoa',
	'San Marino',
	'Sao Tome And Principe',
	'Saudi Arabia',
	'Senegal',
	'Serbia',
	'Seychelles',
	'Sierra Leone',
	'Singapore',
	'Slovakia',
	'Slovenia',
	'Solomon Islands',
	'Somalia',
	'South Africa',
	'South Georgia And The South Sandwich Islands',
	'Spain',
	'Sri Lanka',
	'Sudan',
	'Suriname',
	'Svalbard And Jan Mayen',
	'Swaziland',
	'Sweden',
	'Switzerland',
	'Syrian Arab Republic',
	'Taiwan, Province Of China',
	'Tajikistan',
	'Tanzania, United Republic Of',
	'Thailand',
	'Timor-leste',
	'Togo',
	'Tokelau',
	'Tonga',
	'Trinidad And Tobago',
	'Tunisia',
	'Turkey',
	'Turkmenistan',
	'Turks And Caicos Islands',
	'Tuvalu',
	'Uganda',
	'Ukraine',
	'United Arab Emirates',
	'United Kingdom',
	'United States',
	'United States Minor Outlying Islands',
	'Uruguay',
	'Uzbekistan',
	'Vanuatu',
	'Venezuela',
	'Viet Nam',
	'Virgin Islands, British',
	'Virgin Islands, U.S.',
	'Wallis And Futuna',
	'Western Sahara',
	'Yemen',
	'Zambia',
	'Zimbabwe'
];
